### 각 나라의 GDP 와 의료지수를 비교해서 상관관계가 있는지 확인

<아시아>
대한민국 일본 중국 러시아 싱가폴 캄보디아 필리핀 태국 방글라데시

<중동>
인도 파키스탄 우즈베키스탄 사우디아라비아 쿠웨이트 이스라엘

<아메리카>
미국 멕시코 자메이카 쿠바 브라질 콜롬비아 아르헨티나 칠레 우루과이 페루 에콰도르 \

<유럽>
이탈리아 영국 프랑스 핀란드 체코 네덜란트 페인 노르웨이 스웨덴 폴란드

<오세아니아>
호주 뉴질랜드

<아프리카>
콩고, 짐바브웨, 알제리, 이집트, 모로코, 카메룬, 세네갈, 앙골라, 남아공, 가나

1. 모듈 로딩하고
2. 데이터 준비
3. DF로 저장
4. 전처리 
5. 시각화

In [95]:
# 1. 모듈 로딩
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [96]:
# 2. 데이터 준비
f1_name=r'C:\Users\KDP-23\Desktop\KDT\pandas\new_folder\GLOBAL_DATAFLOW_2005-2015_unicef.xlsx'
f2_name=r'C:\Users\KDP-23\Desktop\KDT\pandas\new_folder\Life Expectancy Data (1).csv'
f3_name=r'C:\Users\KDP-23\Desktop\KDT\pandas\new_folder\P_Data_Extract_From_World_Development_Indicators_worldbank.xlsx'
f4_name=r'C:\Users\KDP-23\Desktop\KDT\pandas\new_folder\saarc_neonatal_mortaility.csv'
f5_name=r'C:\Users\KDP-23\Desktop\KDT\pandas\new_folder\WorldRank.csv'

In [97]:
df2= pd.read_csv(f2_name)
df2.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

'Country' : 나라  
'Year' : 연도  
'Status' :  경제 발전 수준  
'Life expectancy ': 기대수명  
0'Adult Mortality' : 성인 사망률 (인구 100명당 15세-60세 사이에 사망할 확률)  
'infant deaths' : 신생아 사망 (1000명당 신생아 사망)  
0'Alcohol' : 명당 알콜 소비량 (순수 알콜 /l)  
'percentage expenditure' :  1인당GDP 대비 보건 지출 (%)  
'Hepatitis B' : 만 1세중 B형 간염 예방접종률 (%)  
0'Measles ' : 1000명당 매독  
0' BMI ' :전체 인구의 평균 BMI 지수  
'under-five deaths ' :인구 1000명당 5세 이하 사망자 수  
'Polio' : 만 1세 중 소아마비 예방접종률(%)  
'Total expenditure' : 총 정부 지출에서 보건에 대한 정부 지출(%)  
0'Diphtheria ': 디프테리아, 파상풍  및 백일해(DTP3) 예방접종 적용률(%)  
' HIV/AIDS': 0세-4세사이의 사망수 HIV/ADIS 1000개의 생존한 출산당  
'GDP' : 1인당 GDP (/USD)  
'Population': 나라 인구  
0' thinness  10-19 years' :10~19세 소아의 마른 체형 유병률(%)  
0' thinness 5-9 years': 5~9세 소아의 마른 체형 유병률(%)  
0'Income composition of resources' : 자원의 소득구성 측면에서의 인간개발지수(0~1 범위의 지수)  
'Schooling' : 교육연수(년)

GDP로 정렬해서 상위 10개의 선진국과 하위 10개의 개발도산국을 추출해서 유아 사망률을 비교

In [98]:
df2

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [100]:
df2.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [101]:
df2.columns = df2.columns.str.strip()
columns = [
    'Country', 'Year', 'Status', 'Life expectancy', 'infant deaths', 'percentage expenditure',
    'Hepatitis B', 'under-five deaths', 'Polio', 'Total expenditure', 'HIV/AIDS',
    'GDP', 'Population', 'Schooling']
selected_data = df2[columns]

#### 유아 사망률과 연관 된다 생각드는 칼럼 정보:  
- Year: 데이터 기록 연도  
- Status: 국가가 개발된 상태인지 개발 중인지 여부  
- Life expectancy: 출생시 평균 기대수명  
- Infant deaths: 인구 1000명당 영아 사망 수  
- Percentage expenditure: GDP 대비 보건 지출 비율  
- Hepatitis B: 1세 어린이 중 B형 간염 예방접종률 (%)  
- Under-five deaths: 인구 1000명당 5세 미만 사망 수  
- Polio: 1세 어린이 중 소아마비 예방접종률 (%)  
- Total expenditure: 정부의 총 예산 중 보건 지출 비율 (%)  
- HIV/AIDS: 0-4세 사이 HIV/AIDS 사망률 (1000명당 생명)  
- GDP: 국내 총생산(GDP) per capita  
- Population: 국가 인구  
- Schooling: 평균 교육 연수

In [112]:
selected_data

,Country,Year,Status,Life expectancy,infant deaths,percentage expenditure,Hepatitis B,under-five deaths,Polio,Total expenditure,HIV/AIDS,GDP,Population,Schooling
0,Afghanistan,2015,Developing,65.0,62,71.279624,65.0,83,6.0,8.16,0.1,584.259210,33736494.0,10.1
1,Afghanistan,2014,Developing,59.9,64,73.523582,62.0,86,58.0,8.18,0.1,612.696514,327582.0,10.0
2,Afghanistan,2013,Developing,59.9,66,73.219243,64.0,89,62.0,8.13,0.1,631.744976,31731688.0,9.9
3,Afghanistan,2012,Developing,59.5,69,78.184215,67.0,93,67.0,8.52,0.1,669.959000,3696958.0,9.8
4,Afghanistan,2011,Developing,59.2,71,7.097109,68.0,97,68.0,7.87,0.1,63.537231,2978599.0,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,27,0.000000,68.0,42,67.0,7.13,33.6,454.366654,12777511.0,9.2
2934,Zimbabwe,2003,Developing,44.5,26,0.000000,7.0,41,7.0,6.52,36.7,453.351155,12633897.0,9.5
2935,Zimbabwe,2002,Developing,44.8,25,0.000000,73.0,40,73.0,6.53,39.8,57.348340,125525.0,10.0
2936,Zimbabwe,2001,Developing,45.3,25,0.000000,76.0,39,76.0,6.16,42.1,548.587312,12366165.0,9.8
2937,Zimbabwe,2000,Developing,46.0,24,0.000000,79.0,39,78.0,7.10,43.5,547.358878,12222251.0,9.8

아시아 >>>
대한민국 일본 중국 러시아 싱가폴 캄보디아 필리핀 태국 방글라데시
중동 >>>
인도 파키스탄 우즈베키스탄 사우디아라비아 쿠웨이트 이스라엘

Aisa >>> 
"Democratic People's Republic of Korea", "Japan", "China", "Russian Federation", "Singapore", "Cambodia", "Philippines", "Thailand", "Bangladesh",
Middle Aisa >>>
"India", "Pakistan", "Uzbekistan", "Saudi Arabia", "Kuwait", "Israel"

In [103]:
# 아시아 나라 list로 
asian_countries = [
    "Democratic People's Republic of Korea", "Japan", "China", "Russian Federation",
    "Singapore", "Cambodia", "Philippines", "Thailand", "Bangladesh", "India",
    "Pakistan", "Uzbekistan", "Saudi Arabia", "Kuwait", "Israel"]
asia_df = selected_data[selected_data['Country'].isin(asian_countries)].set_index('Country')

# 수치형 데이터만 선택하여 평균으로 결측치를 채우는 함수
def fill_with_mean(group):
    numeric_cols = group.select_dtypes(include=['number']).columns  # 수치형 컬럼만 선택
    group[numeric_cols] = group[numeric_cols].fillna(group[numeric_cols].mean())  # 수치형 컬럼의 평균으로 결측치 채우기
    return group

# 각 국가별로 결측치를 채우기
asia_df_filled = asia_df.groupby('Country',group_keys=False).apply(fill_with_mean)

# 전체 데이터의 평균으로 여전히 남아있는 결측치 채우기 (Status 컬럼 제외)
numeric_cols_global = asia_df_filled.select_dtypes(include=['number']).columns
asia_df_filled[numeric_cols_global] = asia_df_filled[numeric_cols_global].fillna(asia_df_filled[numeric_cols_global].mean())

# 결과 확인
asia_df_filled.info()

<class 'pandas.core.frame.DataFrame'>
Index: 240 entries, Bangladesh to Uzbekistan
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    240 non-null    int64
 1   Status                  240 non-null    object
 2   Life expectancy         240 non-null    float64
 3   infant deaths           240 non-null    int64
 4   percentage expenditure  240 non-null    float64
 5   Hepatitis B             240 non-null    float64
 6   under-five deaths       240 non-null    int64
 7   Polio                   240 non-null    float64
 8   Total expenditure       240 non-null    float64
 9   HIV/AIDS                240 non-null    float64
 10  GDP                     240 non-null    float64
 11  Population              240 non-null    float64
 12  Schooling               240 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 26.2+ KB

In [104]:
asia_df_filled

,Year,Status,Life expectancy,infant deaths,percentage expenditure,Hepatitis B,under-five deaths,Polio,Total expenditure,HIV/AIDS,GDP,Population,Schooling
Country,,,,,,,,,,,,,
Bangladesh,2015,Developing,71.8,92,0.000000,97.000000,113,97.0,2.854667,0.1,121.158120,1612886.0,10.2
Bangladesh,2014,Developing,71.4,98,10.446403,97.000000,121,97.0,2.820000,0.1,184.565430,15945279.0,10.0
Bangladesh,2013,Developing,71.0,104,52.829865,96.000000,130,96.0,2.880000,0.1,951.889453,157571292.0,10.0
Bangladesh,2012,Developing,77.0,111,59.258926,94.000000,139,94.0,3.800000,0.1,856.342857,15572753.0,9.9
Bangladesh,2011,Developing,73.0,118,62.349885,96.000000,150,96.0,3.160000,0.1,835.789341,153911916.0,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,2004,Developing,67.8,24,34.418872,99.000000,29,99.0,5.110000,0.3,465.119887,2586435.0,11.6
Uzbekistan,2003,Developing,67.2,25,28.521358,99.000000,30,99.0,5.170000,0.3,396.129969,2556765.0,11.3
Uzbekistan,2002,Developing,67.1,27,24.994387,62.000000,32,99.0,5.440000,0.2,383.349500,2527185.0,11.0
Uzbekistan,2001,Developing,67.4,28,43.663856,95.642857,34,99.0,5.280000,0.2,456.734892,2496445.0,10.7
Uzbekistan,2000,Developing,67.1,30,48.509417,95.642857,36,99.0,5.290000,0.1,558.221144,24654.0,10.6

아메리카 >>>
미국 멕시코 자메이카 쿠바 브라질 콜롬비아 아르헨티나 칠레 우루과이 페루 에콰도르 

America>>>
'United States of America', 'Mexico', 'Jamaica', 'Cuba', 'Brazil', 'Colombia', 'Argentina', 'Chile', 'Uruguay', 'Peru', 'Ecuador'

In [105]:
america = ['United States of America', 'Mexico', 'Jamaica', 'Cuba',
            'Brazil', 'Colombia', 'Argentina', 'Chile', 'Uruguay', 'Peru', 'Ecuador']
america_df = selected_data[selected_data['Country'].isin(america)].set_index('Country')

# 각 국가별로 결측치를 채우기
america_df_filled = america_df.groupby('Country',group_keys=False).apply(fill_with_mean)

# 전체 데이터의 평균으로 여전히 남아있는 결측치 채우기 (Status 컬럼 제외)
numeric_cols_global = america_df_filled.select_dtypes(include=['number']).columns
america_df_filled[numeric_cols_global] = america_df_filled[numeric_cols_global].fillna(america_df_filled[numeric_cols_global].mean())

# 결과 확인
america_df_filled.info()

<class 'pandas.core.frame.DataFrame'>
Index: 176 entries, Argentina to Uruguay
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    176 non-null    int64
 1   Status                  176 non-null    object
 2   Life expectancy         176 non-null    float64
 3   infant deaths           176 non-null    int64
 4   percentage expenditure  176 non-null    float64
 5   Hepatitis B             176 non-null    float64
 6   under-five deaths       176 non-null    int64
 7   Polio                   176 non-null    float64
 8   Total expenditure       176 non-null    float64
 9   HIV/AIDS                176 non-null    float64
 10  GDP                     176 non-null    float64
 11  Population              176 non-null    float64
 12  Schooling               176 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 19.2+ KB

In [106]:
america_df_filled

,Year,Status,Life expectancy,infant deaths,percentage expenditure,Hepatitis B,under-five deaths,Polio,Total expenditure,HIV/AIDS,GDP,Population,Schooling
Country,,,,,,,,,,,,,
Argentina,2015,Developing,76.3,8,0.000000,94.0,9,93.0,6.912667,0.1,13467.123600,43417765.0,17.3
Argentina,2014,Developing,76.2,8,847.371746,94.0,9,92.0,4.790000,0.1,12245.256450,42981515.0,17.3
Argentina,2013,Developing,76.0,8,1001.796332,94.0,10,99.0,4.990000,0.1,12976.636420,42539925.0,17.3
Argentina,2012,Developing,75.9,9,1133.558003,91.0,10,99.0,5.200000,0.1,12969.771200,4296739.0,17.2
Argentina,2011,Developing,75.7,9,1504.329462,91.0,10,93.0,5.890000,0.1,12726.983600,41656879.0,17.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uruguay,2004,Developing,75.4,1,882.356362,94.0,1,95.0,11.590000,0.1,4117.388530,332496.0,15.5
Uruguay,2003,Developing,75.4,1,160.840014,91.0,1,91.0,6.520000,0.1,3622.522840,3325637.0,15.0
Uruguay,2002,Developing,75.4,1,27.468810,95.0,1,93.0,7.180000,0.1,488.768855,3327773.0,14.7
Uruguay,2001,Developing,75.2,1,421.480428,94.0,1,94.0,7.460000,0.1,6281.377470,332713.0,14.2
Uruguay,2000,Developing,75.1,1,645.958382,92.0,1,92.0,7.820000,0.1,6871.897677,3321245.0,14.0

유럽 >>> 이탈리아 영국 프랑스 핀란드 체코 네덜란트 스페인 노르웨이 스웨덴 폴란드   
EU >>> 'Italy','United Kingdom of Great Britain and Northern Ireland', 'France','Finland','Czechia', 'Netherlands', 'Spain','Norway', 'Sweden', 'Poland'

In [107]:
EU = ['Italy','United Kingdom of Great Britain and Northern Ireland', 'France','Finland','Czechia', 'Netherlands', 'Spain','Norway', 'Sweden', 'Poland']
EU_df = selected_data[selected_data['Country'].isin(EU)].set_index('Country')

# 각 국가별로 결측치를 채우기
EU_df_filled = EU_df.groupby('Country',group_keys=False).apply(fill_with_mean)

# 전체 데이터의 평균으로 여전히 남아있는 결측치 채우기 (Status 컬럼 제외)
numeric_cols_global = america_df_filled.select_dtypes(include=['number']).columns
EU_df_filled[numeric_cols_global] = EU_df_filled[numeric_cols_global].fillna(EU_df_filled[numeric_cols_global].mean())

# 결과 확인
EU_df_filled.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, Czechia to United Kingdom of Great Britain and Northern Ireland
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    160 non-null    int64
 1   Status                  160 non-null    object
 2   Life expectancy         160 non-null    float64
 3   infant deaths           160 non-null    int64
 4   percentage expenditure  160 non-null    float64
 5   Hepatitis B             160 non-null    float64
 6   under-five deaths       160 non-null    int64
 7   Polio                   160 non-null    float64
 8   Total expenditure       160 non-null    float64
 9   HIV/AIDS                160 non-null    float64
 10  GDP                     160 non-null    float64
 11  Population              160 non-null    float64
 12  Schooling               160 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 17.5+ KB

아프리카, 오세아니아 >>> 콩고, 짐바브웨, 알제리, 이집트, 모로코, 카메룬, 세네갈, 앙골라, 남아공, 가나, 호주, 뉴질랜드   
AF,Oceania >>> 'Congo','Zimbabwe','Algeria','Egypt','Morocco','Cameroon','Senegal','Angola','South Africa','Ghana','Australia','New Zealand'

In [108]:
AO = ['Congo','Zimbabwe','Algeria','Egypt','Morocco','Cameroon','Senegal','Angola','South Africa','Ghana','Australia','New Zealand']
AO_df = selected_data[selected_data['Country'].isin(AO)].set_index('Country')

# 각 국가별로 결측치를 채우기
AO_df_filled = AO_df.groupby('Country',group_keys=False).apply(fill_with_mean)

# 전체 데이터의 평균으로 여전히 남아있는 결측치 채우기 (Status 컬럼 제외)
numeric_cols_global = AO_df_filled.select_dtypes(include=['number']).columns
AO_df_filled[numeric_cols_global] = AO_df_filled[numeric_cols_global].fillna(AO_df_filled[numeric_cols_global].mean())

# 결과 확인
AO_df_filled.info()

<class 'pandas.core.frame.DataFrame'>
Index: 192 entries, Algeria to Zimbabwe
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    192 non-null    int64
 1   Status                  192 non-null    object
 2   Life expectancy         192 non-null    float64
 3   infant deaths           192 non-null    int64
 4   percentage expenditure  192 non-null    float64
 5   Hepatitis B             192 non-null    float64
 6   under-five deaths       192 non-null    int64
 7   Polio                   192 non-null    float64
 8   Total expenditure       192 non-null    float64
 9   HIV/AIDS                192 non-null    float64
 10  GDP                     192 non-null    float64
 11  Population              192 non-null    float64
 12  Schooling               192 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 21.0+ KB

'Country' : 나라  
'Year' : 연도  
'Status' :  경제 발전 수준  
'Life expectancy ': 기대수명  
'infant deaths' : 신생아 사망 (1000명당 신생아 사망)  
'percentage expenditure' :  1인당GDP 대비 보건 지출 (%)  
'Hepatitis B' : 만 1세중 B형 간염 예방접종률 (%)  
'under-five deaths ' :인구 1000명당 5세 이하 사망자 수  
'Polio' : 만 1세 중 소아마비 예방접종률(%)  
'Total expenditure' : 총 정부 지출에서 보건에 대한 정부 지출(%)  
' HIV/AIDS': 0세-4세사이의 사망수 HIV/ADIS 1000개의 생존한 출산당  
'GDP' : 1인당 GDP (/USD)  
'Population': 나라 인구
'Schooling' : 교육연수(년)

아시아 >>>
대한민국 일본 중국 러시아 싱가폴 캄보디아 필리핀 태국 방글라데시
중동 >>>
인도 파키스탄 우즈베키스탄 사우디아라비아 쿠웨이트 이스라엘

Aisa >>> 
"Democratic People's Republic of Korea", "Japan", "China", "Russian Federation", "Singapore", "Cambodia", "Philippines", "Thailand", "Bangladesh",
Middle Aisa >>>
"India", "Pakistan", "Uzbekistan", "Saudi Arabia", "Kuwait", "Israel"

In [109]:
asia_df_filled.loc["Democratic People's Republic of Korea"]

,Year,Status,Life expectancy,infant deaths,percentage expenditure,Hepatitis B,under-five deaths,Polio,Total expenditure,HIV/AIDS,GDP,Population,Schooling
Country,,,,,,,,,,,,,
Democratic People's Republic of Korea,2015,Developing,76.0,6,0.0,96.000000,7,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2014,Developing,73.0,6,0.0,93.000000,8,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2013,Developing,71.0,6,0.0,93.000000,8,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2012,Developing,69.8,7,0.0,96.000000,9,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2011,Developing,69.4,8,0.0,94.000000,10,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2010,Developing,69.0,8,0.0,93.000000,10,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2009,Developing,68.7,9,0.0,93.000000,11,98.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2008,Developing,68.6,9,0.0,92.000000,12,98.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2007,Developing,68.5,9,0.0,92.000000,12,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2006,Developing,68.5,10,0.0,96.000000,12,98.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2005,Developing,68.5,10,0.0,92.000000,13,97.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2004,Developing,68.4,11,0.0,98.000000,14,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2003,Developing,68.1,12,0.0,27.000000,15,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2002,Developing,67.6,14,0.0,88.846154,18,99.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2001,Developing,66.6,16,0.0,88.846154,21,98.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625
Democratic People's Republic of Korea,2000,Developing,65.4,18,0.0,88.846154,25,93.0,4.619524,0.1,9713.842724,6.092504e+07,11.990625